package Shuffle.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_EqualToStatement_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_EqualToStatement_InferenceRule() {
  }

  public void applyRule(final SNode equalToStatement, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(equalToStatement, "first", true);
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:b57e8ebe-29cf-4b39-86c1-3d625dfafc54(Shuffle.typesystem)", "5396954793338598853", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:b57e8ebe-29cf-4b39-86c1-3d625dfafc54(Shuffle.typesystem)", "5396954793338596950", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(equalToStatement, "second", true), "r:b57e8ebe-29cf-4b39-86c1-3d625dfafc54(Shuffle.typesystem)", "5396954793338598885", true), _info_12389875345);
    }
  }

  public String getApplicableConceptFQName() {
    return "Shuffle.structure.EqualToStatement";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConcept().getQualifiedName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
