package ShuffleJava.gui;

/*Generated by MPS */

import javax.swing.JPanel;
import ShuffleJava.runtime.CardPile;
import javax.swing.JLabel;
import javax.swing.OverlayLayout;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Graphics;

public class CardPileDisplay extends JPanel {
  private CardPile pile;
  private boolean cascading = false;
  private JLabel stack;
  private JLabel empty;


  public CardPileDisplay(CardPile pile) {
    // JComponent displays either a JButton "Stack", or a JLayeredPane "Cascade" 
    this.setLayout(new OverlayLayout(this));
    this.pile = pile;

    ClassLoader classLoader1 = getClass().getClassLoader();
    this.stack = new JLabel(new ImageIcon(classLoader1.getResource("stack.png")));
    ClassLoader classLoader2 = getClass().getClassLoader();
    this.empty = new JLabel(new ImageIcon(classLoader2.getResource("nothing.png")));

    this.setBackground(new Color(21, 67, 31));

    this.add(this.empty);

  }



  public void cascade(Boolean cascade) {
    this.cascading = cascade;
  }



  public void update() {
    this.removeAll();
    if (this.cascading == false) {
      if (this.pile.size() > 0) {
        this.add(this.stack);
        CardButton topcard = new CardButton(this.pile.getTopCard());
        topcard.setFaceup(this.pile.isFaceup());
        this.add(topcard);
        System.out.println("we have a stacked pile");

      } else {
        this.add(this.empty);
        System.out.println("we have an empty pile");
      }
    } else {
      // cascade 
      // todo: something 
    }
  }



  public void paintComponent(Graphics g) {
    this.update();
    this.setVisible(true);
    super.paintComponent(g);
  }




}
