package ShuffleJava.gui;

/*Generated by MPS */

import javax.swing.JButton;
import ShuffleJava.runtime.Card;
import javax.swing.ImageIcon;
import java.awt.Dimension;

public class CardButton extends JButton {
  private Card card;
  private Boolean faceup;
  private static String imageFaceup;
  private static String imageFacedown = "deckback_small.jpg";
  private ImageIcon iconFacedown;
  private ImageIcon iconFaceup;


  public CardButton(Card card) {
    this.card = card;
    imageFaceup = card.getSuit() + "_" + card.getRank() + ".png";

    ClassLoader classLoader = getClass().getClassLoader();
    iconFacedown = new ImageIcon(classLoader.getResource(imageFacedown));
    iconFaceup = new ImageIcon(classLoader.getResource(imageFaceup));

    this.setIcon(iconFacedown);
    this.setPreferredSize(new Dimension(this.getIcon().getIconWidth(), this.getIcon().getIconHeight()));

    this.setVisible(true);
    // set jbutton size etc 
  }



  public void setFaceup(Boolean faceup) {
    this.faceup = faceup;
    if (faceup) {
      this.setIcon(iconFaceup);
    } else {
      this.setIcon(iconFacedown);
    }
  }
}
