package ShuffleJava.gui;

/*Generated by MPS */

import javax.swing.JButton;
import ShuffleJava.runtime.Card;
import javax.swing.ImageIcon;
import java.awt.Dimension;
import java.awt.Graphics;

public class CardButton extends JButton {
  private Card card;
  private Boolean faceup;
  private static String imageFaceup;
  private static String imageFacedown = "deckback_small.jpg";
  private ImageIcon iconFacedown;
  private ImageIcon iconFaceup;


  public CardButton(Card card) {
    this.card = card;
    imageFaceup = card.getSuit() + "_" + card.getRank() + ".png";
    ClassLoader classLoader = getClass().getClassLoader();
    iconFacedown = new ImageIcon(classLoader.getResource(imageFacedown));
    iconFaceup = new ImageIcon(classLoader.getResource(imageFaceup));
    this.setMaximumSize(new Dimension(this.iconFaceup.getIconWidth(), this.iconFaceup.getIconHeight()));
    this.faceup = false;
  }



  public void setFaceup(Boolean faceup) {
    this.faceup = faceup;
  }



  public void update() {
    if (faceup) {
      this.setIcon(iconFaceup);
    } else {
      this.setIcon(iconFacedown);
    }
  }



  public void paintComponent(Graphics g) {
    super.paintComponent(g);
    this.update();
  }
}
