package ShuffleJava.gui;

/*Generated by MPS */

import javax.swing.JButton;
import javax.swing.ImageIcon;
import java.awt.Dimension;

public class CardButton extends JButton {
  private Boolean faceup;
  private static String imageFaceup;
  private static String imageFacedown = "deckback.jpg";
  private ImageIcon iconFacedown;
  private ImageIcon iconFaceup;


  public CardButton(String rank, String suit) {
    imageFaceup = suit + "_" + rank + ".png";

    ClassLoader classLoader = getClass().getClassLoader();
    iconFacedown = new ImageIcon(classLoader.getResource(imageFacedown));
    iconFaceup = new ImageIcon(classLoader.getResource(imageFaceup));

    this.setIcon(iconFacedown);
    this.setVisible(true);
    // set jbutton size etc 
    this.setMaximumSize(new Dimension(20, 20));
  }



  public void setFaceup(Boolean faceup) {
    this.faceup = faceup;
    if (faceup) {
      this.setIcon(iconFaceup);
    } else {
      this.setIcon(iconFacedown);
    }
  }
}
