package ShuffleJava.gui;

/*Generated by MPS */

import java.awt.Color;
import java.awt.Graphics;

public class EmptyGridCell extends GridCellDisplay {


  public EmptyGridCell() {
    setOpaque(false);
    setBackground(new Color(0, 0, 0, 0));
  }



  public void update(Graphics g) {
  }


}
