package ShuffleJava.gui;

/*Generated by MPS */

import ShuffleJava.runtime.CardPile;

public class Grid {
  public final int GRID_SIZE = 8;
  public CardPile[][] grid = new CardPile[GRID_SIZE][GRID_SIZE];


  public Grid() {
  }



  public void addCardPile(CardPile pile, String horizontal, int vertical) {
    int horizontalCoordinate = stringToCoordinate(horizontal);
    // <node> 
    grid[horizontalCoordinate][vertical] = pile;
  }



  private int stringToCoordinate(String str) {
    int i;
    char c = str.charAt(0);
    switch (c) {
      case 'A':
        i = 0;
        break;
      case 'B':
        i = 1;
        break;
      case 'C':
        i = 2;
        break;
      case 'D':
        i = 3;
        break;
      case 'E':
        i = 4;
        break;
      case 'F':
        i = 5;
        break;
      case 'G':
        i = 6;
        break;
      case 'H':
        i = 7;
        break;
      default:
        i = 0;
    }
    return i;
  }


}
