package ShuffleJava.gui;

/*Generated by MPS */

import javax.swing.JPanel;

public class Grid {
  public final int NUM_GRID_ROWS = 10;
  public final int NUM_GRID_COLOUMNS = 10;
  public GridCellDisplay[][] grid = new GridCellDisplay[NUM_GRID_ROWS][NUM_GRID_COLOUMNS];
  private JPanel canvas;


  public Grid(JPanel canvas) {
    this.canvas = canvas;

    for (int i = 0; i < NUM_GRID_ROWS; i++) {
      for (int j = 0; j < NUM_GRID_COLOUMNS; j++) {
        this.grid[i][j] = new EmptyGridCell();
        canvas.add(this.grid[i][j]);
      }
    }
  }



  public void addToGrid(GridCellDisplay cell, String horizontal, int vertical) {
    int horizontalCoordinate = stringToCoordinate(horizontal);
    // <node> 
    grid[horizontalCoordinate][vertical] = cell;
    int index = horizontalCoordinate * NUM_GRID_ROWS + vertical - 1;

    canvas.remove(index);
    canvas.add(cell, index);
  }



  private int stringToCoordinate(String str) {
    int i;
    char c = str.charAt(0);
    switch (c) {
      case 'A':
        i = 0;
        break;
      case 'B':
        i = 1;
        break;
      case 'C':
        i = 2;
        break;
      case 'D':
        i = 3;
        break;
      case 'E':
        i = 4;
        break;
      case 'F':
        i = 5;
        break;
      case 'G':
        i = 6;
        break;
      case 'H':
        i = 7;
        break;
      default:
        i = 0;
    }
    return i;
  }


}
