package ShuffleJava.gui;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.FlowLayout;

public class ShuffleFrame {
  public final JFrame frame = new JFrame("Shuffle");
  public final JPanel canvas = new JPanel(new GridLayout(10, 10), true);


  public ShuffleFrame() {
    frame.pack();
    frame.setSize(800, 700);
    frame.setLocationRelativeTo(null);
    frame.setLayout(new BorderLayout());

    ClassLoader classLoader = getClass().getClassLoader();
    JLabel background = new JLabel(new ImageIcon(classLoader.getResource("background.png")));
    background.setBackground(Color.GREEN);
    background.setLayout(new FlowLayout());
    frame.add(background);

    canvas.setVisible(true);
    canvas.setOpaque(false);
    background.add(canvas);

    frame.add(background);

    canvas.add(new CardButton("ace", "clubs"));
    canvas.invalidate();
    frame.setVisible(true);
  }
}
