package ShuffleJava.gui;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.Color;

public class ShuffleFrame {
  public final JFrame frame = new JFrame("Shuffle");
  public final JPanel canvas = new JPanel(new GridLayout(10, 10), true);


  public ShuffleFrame() {
    frame.setVisible(true);
    frame.pack();
    frame.setSize(800, 700);
    frame.setLocationRelativeTo(null);
    frame.add(canvas);

    ClassLoader classLoader = getClass().getClassLoader();
    JLabel background = new JLabel(new ImageIcon(classLoader.getResource("bg.jpg")));
    canvas.add(background);
    canvas.setBackground(Color.GREEN);
    canvas.setVisible(true);
  }
}
