package Shuffle.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class NotStatement_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("!");
    appendNode(SLinkOperations.getTarget(node, "orignal", true));
  }
}
