package Shuffle.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Rank {
  A("A", "ace"),
  _2("2", "two"),
  _3("3", "three"),
  _4("4", "four"),
  _5("5", "five"),
  _6("6", "six"),
  _7("7", "seven"),
  _8("8", "eight"),
  _9("9", "nine"),
  _10("10", "ten"),
  J("J", "jack"),
  Q("Q", "queen"),
  K("K", "king");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Rank> getConstants() {
    List<Rank> list = ListSequence.fromList(new LinkedList<Rank>());
    ListSequence.fromList(list).addElement(Rank.A);
    ListSequence.fromList(list).addElement(Rank._2);
    ListSequence.fromList(list).addElement(Rank._3);
    ListSequence.fromList(list).addElement(Rank._4);
    ListSequence.fromList(list).addElement(Rank._5);
    ListSequence.fromList(list).addElement(Rank._6);
    ListSequence.fromList(list).addElement(Rank._7);
    ListSequence.fromList(list).addElement(Rank._8);
    ListSequence.fromList(list).addElement(Rank._9);
    ListSequence.fromList(list).addElement(Rank._10);
    ListSequence.fromList(list).addElement(Rank.J);
    ListSequence.fromList(list).addElement(Rank.Q);
    ListSequence.fromList(list).addElement(Rank.K);
    return list;
  }

  public static Rank getDefault() {
    return Rank.A;
  }

  public static Rank parseValue(String value) {
    if (value == null) {
      return Rank.getDefault();
    }
    if (value.equals(Rank.A.getValueAsString())) {
      return Rank.A;
    }
    if (value.equals(Rank._2.getValueAsString())) {
      return Rank._2;
    }
    if (value.equals(Rank._3.getValueAsString())) {
      return Rank._3;
    }
    if (value.equals(Rank._4.getValueAsString())) {
      return Rank._4;
    }
    if (value.equals(Rank._5.getValueAsString())) {
      return Rank._5;
    }
    if (value.equals(Rank._6.getValueAsString())) {
      return Rank._6;
    }
    if (value.equals(Rank._7.getValueAsString())) {
      return Rank._7;
    }
    if (value.equals(Rank._8.getValueAsString())) {
      return Rank._8;
    }
    if (value.equals(Rank._9.getValueAsString())) {
      return Rank._9;
    }
    if (value.equals(Rank._10.getValueAsString())) {
      return Rank._10;
    }
    if (value.equals(Rank.J.getValueAsString())) {
      return Rank.J;
    }
    if (value.equals(Rank.Q.getValueAsString())) {
      return Rank.Q;
    }
    if (value.equals(Rank.K.getValueAsString())) {
      return Rank.K;
    }
    return Rank.getDefault();
  }

  private String myValue;

  Rank(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
