package Shuffle.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("Shuffle.structure.AndStatement").super_("Shuffle.structure.LogicalExpression").parents("Shuffle.structure.LogicalExpression").children(new String[]{"first", "second"}, new boolean[]{false, false}).create();
      case 1:
        return new ConceptDescriptorBuilder("Shuffle.structure.Card").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").properties("rank", "suit").create();
      case 2:
        return new ConceptDescriptorBuilder("Shuffle.structure.CardCollection").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").children(new String[]{"cards"}, new boolean[]{true}).abstract_().create();
      case 3:
        return new ConceptDescriptorBuilder("Shuffle.structure.Command").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").abstract_().create();
      case 4:
        return new ConceptDescriptorBuilder("Shuffle.structure.CommandBlock").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").properties("name").children(new String[]{"body"}, new boolean[]{true}).abstract_().create();
      case 5:
        return new ConceptDescriptorBuilder("Shuffle.structure.Deal").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").children(new String[]{"deck"}, new boolean[]{false}).alias("deal", "").create();
      case 6:
        return new ConceptDescriptorBuilder("Shuffle.structure.Deck").super_("Shuffle.structure.CardCollection").parents("Shuffle.structure.CardCollection", "jetbrains.mps.lang.core.structure.INamedConcept").alias("deck", "").create();
      case 7:
        return new ConceptDescriptorBuilder("Shuffle.structure.DeckReference").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").references("deck").create();
      case 8:
        return new ConceptDescriptorBuilder("Shuffle.structure.ElseIfStatement").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").children(new String[]{"condition", "body"}, new boolean[]{false, true}).alias("else if", "").create();
      case 9:
        return new ConceptDescriptorBuilder("Shuffle.structure.ElseStatement").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").children(new String[]{"body"}, new boolean[]{true}).alias("else", "").create();
      case 10:
        return new ConceptDescriptorBuilder("Shuffle.structure.EqualToStatement").super_("Shuffle.structure.LogicalExpression").parents("Shuffle.structure.LogicalExpression").children(new String[]{"first", "second"}, new boolean[]{false, false}).create();
      case 11:
        return new ConceptDescriptorBuilder("Shuffle.structure.ForStatement").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").alias("for", "").create();
      case 12:
        return new ConceptDescriptorBuilder("Shuffle.structure.GreaterThanStatement").super_("Shuffle.structure.LogicalExpression").parents("Shuffle.structure.LogicalExpression").children(new String[]{"first", "second"}, new boolean[]{false, false}).create();
      case 13:
        return new ConceptDescriptorBuilder("Shuffle.structure.Hand").super_("Shuffle.structure.CardCollection").parents("Shuffle.structure.CardCollection").create();
      case 14:
        return new ConceptDescriptorBuilder("Shuffle.structure.IfStatement").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").children(new String[]{"condition", "body", "elseIf", "else"}, new boolean[]{false, true, true, false}).alias("if", "").create();
      case 15:
        return new ConceptDescriptorBuilder("Shuffle.structure.LessThanStatement").super_("Shuffle.structure.LogicalExpression").parents("Shuffle.structure.LogicalExpression").children(new String[]{"first", "second"}, new boolean[]{false, false}).create();
      case 16:
        return new ConceptDescriptorBuilder("Shuffle.structure.LogicalExpression").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").create();
      case 17:
        return new ConceptDescriptorBuilder("Shuffle.structure.Main").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.execution.util.structure.IMainClass", "jetbrains.mps.lang.core.structure.ScopeProvider").children(new String[]{"setupBlock", "winConditionBlock"}, new boolean[]{false, false}).create();
      case 18:
        return new ConceptDescriptorBuilder("Shuffle.structure.NotStatement").super_("Shuffle.structure.LogicalExpression").parents("Shuffle.structure.LogicalExpression").children(new String[]{"orignal"}, new boolean[]{false}).create();
      case 19:
        return new ConceptDescriptorBuilder("Shuffle.structure.Number").super_("Shuffle.structure.Variable").parents("Shuffle.structure.Variable", "jetbrains.mps.lang.core.structure.INamedConcept").properties("value").children(new String[]{"expression"}, new boolean[]{false}).create();
      case 20:
        return new ConceptDescriptorBuilder("Shuffle.structure.NumberAssignment").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").children(new String[]{"expression", "variable"}, new boolean[]{false, false}).alias("set", "").create();
      case 21:
        return new ConceptDescriptorBuilder("Shuffle.structure.NumberReference").super_("jetbrains.mps.baseLanguage.structure.Expression").parents("jetbrains.mps.baseLanguage.structure.Expression").references("number").create();
      case 22:
        return new ConceptDescriptorBuilder("Shuffle.structure.OrStatement").super_("Shuffle.structure.LogicalExpression").parents("Shuffle.structure.LogicalExpression").children(new String[]{"first", "second"}, new boolean[]{false, false}).create();
      case 23:
        return new ConceptDescriptorBuilder("Shuffle.structure.Pile").super_("Shuffle.structure.CardCollection").parents("Shuffle.structure.CardCollection").properties("isFaceUp").alias("pile", "").create();
      case 24:
        return new ConceptDescriptorBuilder("Shuffle.structure.Player").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").children(new String[]{"hand"}, new boolean[]{false}).create();
      case 25:
        return new ConceptDescriptorBuilder("Shuffle.structure.SetupBlock").super_("Shuffle.structure.CommandBlock").parents("Shuffle.structure.CommandBlock").alias("setup board", "").create();
      case 26:
        return new ConceptDescriptorBuilder("Shuffle.structure.ShuffleDeck").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").children(new String[]{"deck"}, new boolean[]{false}).alias("shuffle", "").create();
      case 27:
        return new ConceptDescriptorBuilder("Shuffle.structure.Variable").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").abstract_().create();
      case 28:
        return new ConceptDescriptorBuilder("Shuffle.structure.WhileStatement").super_("Shuffle.structure.Command").parents("Shuffle.structure.Command").children(new String[]{"condition", "body"}, new boolean[]{false, true}).alias("while", "").create();
      case 29:
        return new ConceptDescriptorBuilder("Shuffle.structure.WinConditionBlock").super_("Shuffle.structure.CommandBlock").parents("Shuffle.structure.CommandBlock").alias("win condition", "").create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"Shuffle.structure.AndStatement", "Shuffle.structure.Card", "Shuffle.structure.CardCollection", "Shuffle.structure.Command", "Shuffle.structure.CommandBlock", "Shuffle.structure.Deal", "Shuffle.structure.Deck", "Shuffle.structure.DeckReference", "Shuffle.structure.ElseIfStatement", "Shuffle.structure.ElseStatement", "Shuffle.structure.EqualToStatement", "Shuffle.structure.ForStatement", "Shuffle.structure.GreaterThanStatement", "Shuffle.structure.Hand", "Shuffle.structure.IfStatement", "Shuffle.structure.LessThanStatement", "Shuffle.structure.LogicalExpression", "Shuffle.structure.Main", "Shuffle.structure.NotStatement", "Shuffle.structure.Number", "Shuffle.structure.NumberAssignment", "Shuffle.structure.NumberReference", "Shuffle.structure.OrStatement", "Shuffle.structure.Pile", "Shuffle.structure.Player", "Shuffle.structure.SetupBlock", "Shuffle.structure.ShuffleDeck", "Shuffle.structure.Variable", "Shuffle.structure.WhileStatement", "Shuffle.structure.WinConditionBlock"};
}
