package Shuffle.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Suit {
  S("S", "spades"),
  H("H", "hearts"),
  C("C", "clubs"),
  D("D", "diamonds");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Suit> getConstants() {
    List<Suit> list = ListSequence.fromList(new LinkedList<Suit>());
    ListSequence.fromList(list).addElement(Suit.S);
    ListSequence.fromList(list).addElement(Suit.H);
    ListSequence.fromList(list).addElement(Suit.C);
    ListSequence.fromList(list).addElement(Suit.D);
    return list;
  }

  public static Suit getDefault() {
    return Suit.S;
  }

  public static Suit parseValue(String value) {
    if (value == null) {
      return Suit.getDefault();
    }
    if (value.equals(Suit.S.getValueAsString())) {
      return Suit.S;
    }
    if (value.equals(Suit.H.getValueAsString())) {
      return Suit.H;
    }
    if (value.equals(Suit.C.getValueAsString())) {
      return Suit.C;
    }
    if (value.equals(Suit.D.getValueAsString())) {
      return Suit.D;
    }
    return Suit.getDefault();
  }

  private String myValue;

  Suit(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
