package Shuffle.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Suit {
  spades("\u2660", "spades"),
  hearts("\u2665", "hearts"),
  clubs("\u2663", "clubs"),
  diamonds("\u2666", "diamonds");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Suit> getConstants() {
    List<Suit> list = ListSequence.fromList(new LinkedList<Suit>());
    ListSequence.fromList(list).addElement(Suit.spades);
    ListSequence.fromList(list).addElement(Suit.hearts);
    ListSequence.fromList(list).addElement(Suit.clubs);
    ListSequence.fromList(list).addElement(Suit.diamonds);
    return list;
  }

  public static Suit getDefault() {
    return Suit.spades;
  }

  public static Suit parseValue(String value) {
    if (value == null) {
      return Suit.getDefault();
    }
    if (value.equals(Suit.spades.getValueAsString())) {
      return Suit.spades;
    }
    if (value.equals(Suit.hearts.getValueAsString())) {
      return Suit.hearts;
    }
    if (value.equals(Suit.clubs.getValueAsString())) {
      return Suit.clubs;
    }
    if (value.equals(Suit.diamonds.getValueAsString())) {
      return Suit.diamonds;
    }
    return Suit.getDefault();
  }

  private String myValue;

  Suit(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
