package ShuffleJava.gui_2;

/*Generated by MPS */

import ShuffleJava.runtime.CardPile;
import java.awt.Color;
import java.awt.Graphics;

public abstract class CardPileDisplay {

  protected CardPile pile;
  protected Color bgcolour;
  protected ClassLoader classLoader1;

  protected int dragStartx;
  protected int dragStarty;

  protected int dragOffsetx = 0;
  protected int dragOffsety = 0;



  protected int getDragOffsetx() {
    return dragOffsetx;
  }



  protected int getDragOffsety() {
    return dragOffsety;
  }




  protected CardPileDisplay(CardPile pile) {
    this.pile = pile;
    this.classLoader1 = getClass().getClassLoader();
    this.bgcolour = new Color(21, 67, 31);
  }



  protected void draw(Graphics g, int x, int y) {
    g.setColor(this.bgcolour);
  }



  public int getCardIndexAt(int x, int y) {
    return -1;
  }



  public void startDrag(int x, int y) {
    dragStartx = x;
    dragStarty = y;

  }



  public void drag(int x, int y) {
    dragOffsetx = x - dragStartx;
    dragOffsety = y - dragStarty;

  }



  public void endDrag() {
    dragOffsetx = 0;
    dragOffsety = 0;

  }



}
