package ShuffleJava.gui_2;

/*Generated by MPS */

import java.awt.image.BufferedImage;
import ShuffleJava.runtime.Card;
import java.awt.Color;
import javax.imageio.ImageIO;
import java.io.IOException;
import java.awt.Graphics;

public class CardDisplay implements ShuffleDraw {
  public static int CARD_HEIGHT = 70;
  public static int CARD_WIDTH = 48;

  private BufferedImage img;
  private Card card;
  protected ClassLoader classLoader;
  protected Color selectColor = new Color(84, 141, 255, 101);


  public CardDisplay(Card c) {
    setCard(c);
  }



  public void setCard(Card c) {
    card = c;
  }



  private void update() {
    String imgName;
    imgName = card.getSuit() + "_" + card.getRank() + ".png";
    classLoader = getClass().getClassLoader();
    try {
      img = ImageIO.read(classLoader.getResource(imgName));
    } catch (IOException e) {
      System.out.println("ERROR! StackedPileDisplay: topcard image not found");
    }
  }



  public int getWidth() {
    return CARD_WIDTH;
  }

  public int getHeight() {
    return CARD_HEIGHT;
  }



  public void draw(Graphics g, int x, int y) {
    update();
    g.drawImage(img, x, y, Color.WHITE, null);
    if (card.isSelected()) {
      g.setColor(this.selectColor);
      g.fillRect(x, y, getWidth(), getHeight());
    }
  }



  public void click(int x, int y) {
  }
}
