package ShuffleJava.gui_2;

/*Generated by MPS */

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;

public class Console extends JPanel {
  private int HEIGHT = 700;
  private int WIDTH = 200;

  public JScrollPane console;
  private JTextPane consoleText;


  public Console() {
    consoleText = new JTextPane();
    consoleText.setOpaque(false);
    consoleText.setEditable(false);
    consoleText.setForeground(Color.YELLOW);
    consoleText.setPreferredSize(new Dimension(WIDTH, HEIGHT));

    console = new JScrollPane(consoleText, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    console.setBackground(Color.BLACK);
    console.getViewport().setBackground(Color.BLACK);

    console.setBorder(BorderFactory.createEmptyBorder());
    consoleText.setBorder(BorderFactory.createEmptyBorder());

    this.add(console);
    console.setVisible(true);
    consoleText.setVisible(true);

    this.invalidate();
    this.setVisible(true);
  }



  public void printToConsole(Object... text) {
    StringBuilder sb = new StringBuilder(consoleText.getText());
    sb.append(">");
    for (int i = 0; i < text.length; i++) {
      sb.append(text[i].toString());
    }
    sb.append("\n");
    consoleText.setText(sb.toString());

  }



}
