package ShuffleJava.gui_2;

/*Generated by MPS */

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import java.awt.Color;
import java.awt.Dimension;

public class Console extends JPanel {
  private int HEIGHT = 700;
  private int WIDTH = 200;

  public JScrollPane console;
  private JTextPane consoleText;


  public Console() {
    consoleText = new JTextPane();
    consoleText.setOpaque(false);
    consoleText.setEditable(false);
    consoleText.setForeground(Color.YELLOW);
    consoleText.setPreferredSize(new Dimension(WIDTH, HEIGHT));
    consoleText.setVisible(true);

    console = new JScrollPane(consoleText, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    console = new JScrollPane();
    console.setBackground(Color.BLACK);
    console.getViewport().setBackground(Color.BLACK);
    console.setOpaque(false);
    console.setVisible(true);

    this.add(console);
    this.add(consoleText);

    this.invalidate();
    this.setVisible(true);
  }



  public void printToConsole(Object... text) {
    String output = consoleText + "<";
    for (int i = 0; i < text.length; i++) {
      output = output + text[i].toString();
    }
    output = output + "\n";
  }



}
