package ShuffleJava.gui_2;

/*Generated by MPS */

import ShuffleJava.runtime.CardPile;
import java.awt.Graphics;

public class HiddenPileDisplay extends CardPileDisplay implements ShuffleDraw {
  public HiddenPileDisplay(CardPile pile) {
    super(pile);
  }



  public int getWidth() {
    return 0;
  }



  public int getHeight() {
    return 0;
  }



  public void draw(Graphics g, int x, int y) {
  }




  public void click(int x, int y) {
  }


}
