package ShuffleJava.gui_2;

/*Generated by MPS */

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

public class Popup {
  private ArrayList<String> options;
  private String message;
  private JOptionPane dialogBox;
  private JFrame frame = new JFrame("Popup frame");



  public Popup(String message, ArrayList<String> options) {
    this.message = message;
    this.dialogBox = new JOptionPane();
    this.options = options;
  }



  public int show() {
    int result = JOptionPane.showOptionDialog(frame, message, "Popup!", 0, JOptionPane.PLAIN_MESSAGE, null, options.toArray(), options.toArray()[0]);
    return result;
  }


}
