package ShuffleJava.gui_2;

/*Generated by MPS */

import java.awt.Graphics;

public interface ShuffleDraw {
  public void draw(Graphics g, int x, int y);
  public void click(int x, int y);
  public int getHeight();
  public int getWidth();

}
