package ShuffleJava.gui_2;

/*Generated by MPS */

import javax.swing.JFrame;
import ShuffleJava.runtime.GameState;
import javax.swing.BoxLayout;

public class ShuffleFrame {
  public static int WIDTH = 1000;
  public static int HEIGHT = 700;
  public static int CANVAS_WIDTH = 760;
  public static int CANVAS_HEIGHT = 660;

  public final JFrame frame = new JFrame("Shuffle");
  public Canvas canvas;
  public Console console;


  public void redraw() {
    frame.validate();
    frame.repaint();
  }



  public ShuffleFrame(GameState g) {
    frame.pack();
    frame.setSize(WIDTH, HEIGHT);
    frame.setLocationRelativeTo(null);
    frame.setLayout(new BoxLayout(frame.getContentPane(), BoxLayout.X_AXIS));

    ClassLoader classLoader = getClass().getClassLoader();

    console = new Console();
    frame.getContentPane().add(console);

    // it turns out the frame size is its OUTSIDE, so shrink canvas to fit 
    canvas = new Canvas(CANVAS_WIDTH, CANVAS_HEIGHT, g);
    frame.getContentPane().add(canvas);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


    canvas.invalidate();
    console.invalidate();
    frame.setVisible(true);
  }



  public Canvas getCanvas() {
    return this.canvas;
  }


}
