package ShuffleJava.gui_2;

/*Generated by MPS */

import java.awt.event.MouseAdapter;
import java.util.List;
import java.util.Map;
import ShuffleJava.runtime.GameState;
import java.awt.event.MouseEvent;
import java.awt.Component;
import java.awt.Cursor;
import ShuffleJava.runtime.CardPileUtil;
import java.awt.event.MouseWheelEvent;

public class ShuffleMouseEvents extends MouseAdapter {

  private List<ShuffleDraw> components;
  private Map<ShuffleDraw, Float[]> locations;
  private Integer[] canvasDimensions;
  private CardPileDisplay draggingPile;
  private GameState gameState;
  private boolean dragging = false;
  private int clickedIndex = -1;


  public ShuffleMouseEvents(List<ShuffleDraw> components, Map<ShuffleDraw, Float[]> locations, Integer[] canvasDimensions, GameState gameState) {
    this.components = components;
    this.locations = locations;
    this.canvasDimensions = canvasDimensions;
    this.gameState = gameState;
  }



  @Override
  public void mouseClicked(MouseEvent event) {
    super.mouseClicked(event);
  }

  @Override
  public void mousePressed(MouseEvent event) {
    ShuffleDraw clickedObj = figureOutWhatObject(event.getX(), event.getY());
    if (clickedObj != null) {
      if (clickedObj instanceof CardPileDisplay && ((CardPileDisplay) clickedObj).pile.isSelectable()) {
        draggingPile = ((CardPileDisplay) clickedObj);
        int x = getAbsoluteX(canvasDimensions[0], locations.get(clickedObj)[0]);
        int y = getAbsoluteY(canvasDimensions[1], locations.get(clickedObj)[1]);
        x = event.getX() - x;
        y = event.getY() - y;
        int i = draggingPile.getCardIndexAt(x, y);
        if (!(draggingPile.pile.getCard(i).isSelected())) {
          draggingPile.pile.toggleSelection(i);
        } else {
          clickedIndex = i;
        }
        ((Component) event.getSource()).repaint();

        dragging = true;
        draggingPile.startDrag(event.getX(), event.getY());
        ((Component) event.getSource()).setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
      } else {
        clickedObj.click(event.getX(), event.getY());
      }
    }

  }

  @Override
  public void mouseReleased(MouseEvent event) {
    if (dragging == true) {
      ShuffleDraw clickedObj = figureOutWhatObject(event.getX(), event.getY());
      if (clickedObj != null) {
        if (clickedObj instanceof CardPileDisplay) {
          CardPileDisplay dropPile = ((CardPileDisplay) clickedObj);
          if (gameState.isValidPileDrag(draggingPile.pile.getName(), dropPile.pile.getName())) {
            CardPileUtil.move(draggingPile.pile, dropPile.pile, gameState);
          } else if (draggingPile == dropPile) {
            int x = getAbsoluteX(canvasDimensions[0], locations.get(clickedObj)[0]);
            int y = getAbsoluteY(canvasDimensions[1], locations.get(clickedObj)[1]);
            y = event.getY() - y;
            x = event.getX() - x;
            int i = draggingPile.getCardIndexAt(x, y);
            if (i == clickedIndex) {
              draggingPile.pile.toggleSelection(i);
            }
          }
        }
      }
      draggingPile.endDrag();
    }
    clickedIndex = -1;
    ((Component) event.getSource()).setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    dragging = false;
    ((Component) event.getSource()).repaint();

  }

  @Override
  public void mouseEntered(MouseEvent event) {
    super.mouseEntered(event);
  }

  @Override
  public void mouseExited(MouseEvent event) {
    super.mouseExited(event);
  }

  @Override
  public void mouseWheelMoved(MouseWheelEvent event) {
    super.mouseWheelMoved(event);
  }

  @Override
  public void mouseDragged(MouseEvent event) {
    if (dragging) {
      draggingPile.drag(event.getX(), event.getY());
      ((Component) event.getSource()).repaint();

    }
    super.mouseDragged(event);
  }

  @Override
  public void mouseMoved(MouseEvent event) {
    ShuffleDraw clickedObj = figureOutWhatObject(event.getX(), event.getY());
    if (clickedObj != null) {
      if (clickedObj instanceof CardPileDisplay) {
        CardPileDisplay pile = ((CardPileDisplay) clickedObj);
        if (pile.pile.isSelectable()) {
          ((Component) event.getSource()).setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        } else {
          ((Component) event.getSource()).setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
      } else if (clickedObj instanceof ButtonDisplay) {
        ((Component) event.getSource()).setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
      }
    } else {
      ((Component) event.getSource()).setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }

  }



  private boolean between(int low, int num, int high) {
    return (num > low) && num < high;
  }




  /**
   * stub out to figure out what component the mouse interacted with
   */
  private ShuffleDraw figureOutWhatObject(int x, int y) {
    for (ShuffleDraw c : components) {
      int absx = getAbsoluteX(canvasDimensions[0], locations.get(c)[0]);
      int absy = getAbsoluteY(canvasDimensions[1], locations.get(c)[1]);
      if (between(absx, x, absx + c.getWidth()) && between(absy, y, absy + c.getHeight())) {
        return c;
      }
    }
    return null;
  }



  private int getAbsoluteX(int canvasWidth, float proportionVal) {
    return (int) (proportionVal * canvasWidth);
  }



  private int getAbsoluteY(int canvasHeight, float proportionVal) {
    return (int) (proportionVal * canvasHeight);
  }




}
