package Shuffle.behavior;

/*Generated by MPS */


public class AndStatement_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public AndStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.AndStatement";
  }
}
