package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 3:
        return new Deck_BehaviorDescriptor();
      case 6:
        return new Main_BehaviorDescriptor();
      case 0:
        return new Card_BehaviorDescriptor();
      case 11:
        return new Player_BehaviorDescriptor();
      case 13:
        return new Suit_BehaviorDescriptor();
      case 7:
        return new Number_BehaviorDescriptor();
      case 9:
        return new NumberReference_BehaviorDescriptor();
      case 8:
        return new NumberAssignment_BehaviorDescriptor();
      case 4:
        return new DeckReference_BehaviorDescriptor();
      case 12:
        return new ShuffleDeck_BehaviorDescriptor();
      case 2:
        return new Deal_BehaviorDescriptor();
      case 1:
        return new CardCollection_BehaviorDescriptor();
      case 10:
        return new Pile_BehaviorDescriptor();
      case 5:
        return new Hand_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"Shuffle.structure.Card", "Shuffle.structure.CardCollection", "Shuffle.structure.Deal", "Shuffle.structure.Deck", "Shuffle.structure.DeckReference", "Shuffle.structure.Hand", "Shuffle.structure.Main", "Shuffle.structure.Number", "Shuffle.structure.NumberAssignment", "Shuffle.structure.NumberReference", "Shuffle.structure.Pile", "Shuffle.structure.Player", "Shuffle.structure.ShuffleDeck", "Shuffle.structure.Suit"};
}
