package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class BooleanExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public BooleanExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.BooleanExpression";
  }
}
