package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public abstract class BooleanExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public BooleanExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.BooleanExpression";
  }
}
