package Shuffle.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Card_Behavior {
  public static void init(SNode thisNode) {
  }

  public static void call_setRank_6640477685921374830(SNode thisNode, SNode rank) {
    SPropertyOperations.set(thisNode, "rank", "RANK");
  }

  public static void call_setSuit_6640477685921384290(SNode thisNode, SNode suit) {
    SPropertyOperations.set(thisNode, "suit", "SUIT");
  }
}
