package Shuffle.behavior;

/*Generated by MPS */


public class CardSet_BehaviorDescriptor extends CardCollection_BehaviorDescriptor {
  public CardSet_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.CardSet";
  }
}
