package Shuffle.behavior;

/*Generated by MPS */


public abstract class CardCollection_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public CardCollection_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.CardCollection";
  }
}
