package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CardCollection_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CardCollection_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.CardCollection";
  }
}
