package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class CardCollectionReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CardCollectionReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.CardCollectionReference";
  }
}
