package Shuffle.behavior;

/*Generated by MPS */


public abstract class CommandBlock_BehaviorDescriptor extends Block_BehaviorDescriptor {
  public CommandBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.CommandBlock";
  }
}
