package Shuffle.behavior;

/*Generated by MPS */


public class ConditionBlock_BehaviorDescriptor extends Block_BehaviorDescriptor {
  public ConditionBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.ConditionBlock";
  }
}
