package Shuffle.behavior;

/*Generated by MPS */


public class Deal_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public Deal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Deal";
  }
}
