package Shuffle.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Deck_Behavior {
  public static void init(SNode thisNode) {
    for (SNode rank : ListSequence.fromList(SEnumOperations.getEnumMembers(SEnumOperations.getEnum("r:c7d67aeb-edcf-4a0e-a53e-e5e3ee2ab3bf(Shuffle.structure)", "Rank")))) {
      for (SNode suit : ListSequence.fromList(SEnumOperations.getEnumMembers(SEnumOperations.getEnum("r:c7d67aeb-edcf-4a0e-a53e-e5e3ee2ab3bf(Shuffle.structure)", "Suit")))) {
        SLinkOperations.addNewChild(thisNode, "cards", "Shuffle.structure.Card");
        Card_Behavior.call_setRank_6640477685921374830(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "cards", true)).last(), rank);
        Card_Behavior.call_setSuit_6640477685921384290(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "cards", true)).last(), suit);
      }
    }
  }
}
