package Shuffle.behavior;

/*Generated by MPS */


public class Deck_BehaviorDescriptor extends CardCollection_BehaviorDescriptor {
  public Deck_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Deck";
  }
}
