package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class Deck_BehaviorDescriptor extends Variable_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public Deck_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Deck";
  }
}
