package Shuffle.behavior;

/*Generated by MPS */


public class DeckReference_BehaviorDescriptor extends CardCollectionReference_BehaviorDescriptor {
  public DeckReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.DeckReference";
  }
}
