package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DeckReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DeckReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.DeckReference";
  }
}
