package Shuffle.behavior;

/*Generated by MPS */


public class ElseIfStatement_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public ElseIfStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.ElseIfStatement";
  }
}
