package Shuffle.behavior;

/*Generated by MPS */


public class ElseStatement_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public ElseStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.ElseStatement";
  }
}
