package Shuffle.behavior;

/*Generated by MPS */


public class EmptyLine_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public EmptyLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.EmptyLine";
  }
}
