package Shuffle.behavior;

/*Generated by MPS */


public class EqualToStatement_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public EqualToStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.EqualToStatement";
  }
}
