package Shuffle.behavior;

/*Generated by MPS */


public class ForStatement_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public ForStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.ForStatement";
  }
}
