package Shuffle.behavior;

/*Generated by MPS */


public class GreaterThanStatement_BehaviorDescriptor extends LogicalExpression_BehaviorDescriptor {
  public GreaterThanStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.GreaterThanStatement";
  }
}
