package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class GreaterThanStatement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public GreaterThanStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.GreaterThanStatement";
  }
}
