package Shuffle.behavior;

/*Generated by MPS */


public class Hand_BehaviorDescriptor extends CardCollection_BehaviorDescriptor {
  public Hand_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Hand";
  }
}
