package Shuffle.behavior;

/*Generated by MPS */


public class IfStatement_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public IfStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.IfStatement";
  }
}
