package Shuffle.behavior;

/*Generated by MPS */


public class LessThanStatement_BehaviorDescriptor extends BooleanExpression_BehaviorDescriptor {
  public LessThanStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.LessThanStatement";
  }
}
