package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LogicalExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public LogicalExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.LogicalExpression";
  }
}
