package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Main_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Main_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Main";
  }
}
