package Shuffle.behavior;

/*Generated by MPS */


public class Move_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public Move_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Move";
  }
}
