package Shuffle.behavior;

/*Generated by MPS */


public class NotStatement_BehaviorDescriptor extends BooleanExpression_BehaviorDescriptor {
  public NotStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.NotStatement";
  }
}
