package Shuffle.behavior;

/*Generated by MPS */


public class NumberAssignment_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public NumberAssignment_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.NumberAssignment";
  }
}
