package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class NumberReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public NumberReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.NumberReference";
  }
}
