package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class Number_BehaviorDescriptor extends Variable_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public Number_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Number";
  }
}
