package Shuffle.behavior;

/*Generated by MPS */


public class NumPlayers_BehaviorDescriptor extends Number_BehaviorDescriptor {
  public NumPlayers_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.NumPlayers";
  }
}
