package Shuffle.behavior;

/*Generated by MPS */


public class OrStatement_BehaviorDescriptor extends BooleanExpression_BehaviorDescriptor {
  public OrStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.OrStatement";
  }
}
