package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PileReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PileReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.PileReference";
  }
}
