package Shuffle.behavior;

/*Generated by MPS */


public class PileReference_BehaviorDescriptor extends CardCollectionReference_BehaviorDescriptor {
  public PileReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.PileReference";
  }
}
