package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class Pile_BehaviorDescriptor extends CardCollection_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public Pile_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Pile";
  }
}
