package Shuffle.behavior;

/*Generated by MPS */


public class Pile_BehaviorDescriptor extends CardCollection_BehaviorDescriptor {
  public Pile_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.Pile";
  }
}
