package Shuffle.behavior;

/*Generated by MPS */


public class PlayerTurnBlock_BehaviorDescriptor extends CommandBlock_BehaviorDescriptor {
  public PlayerTurnBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.PlayerTurnBlock";
  }
}
