package Shuffle.behavior;

/*Generated by MPS */


public class SetupBlock_BehaviorDescriptor extends CommandBlock_BehaviorDescriptor {
  public SetupBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.SetupBlock";
  }
}
