package Shuffle.behavior;

/*Generated by MPS */


public class ShuffleDeck_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public ShuffleDeck_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.ShuffleDeck";
  }
}
