package Shuffle.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class VariableReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public VariableReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.VariableReference";
  }
}
