package Shuffle.behavior;

/*Generated by MPS */


public class WhileStatement_BehaviorDescriptor extends Command_BehaviorDescriptor {
  public WhileStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.WhileStatement";
  }
}
