package Shuffle.behavior;

/*Generated by MPS */


public class WinConditionBlock_BehaviorDescriptor extends ConditionBlock_BehaviorDescriptor {
  public WinConditionBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Shuffle.structure.WinConditionBlock";
  }
}
