package Shuffle;

/*Generated by MPS */


public class map_Main {


  public static void main(String[] args) {
    // Game Loop 
    while (true) {
      // win condition 
      if (2 == 8) {
        break;
      }
    }

    // Game Finished 
    System.out.println("Game Finished.");
  }
}
