package Crazy8s;

/*Generated by MPS */

import ShuffleJava.runtime.ShuffleException;
import ShuffleJava.gui.ShuffleFrame;
import ShuffleJava.runtime.Card;
import ShuffleJava.runtime.GameState;
import ShuffleJava.runtime.Printer;

public class map_Main {


  public static void executeGame() throws ShuffleException {
    ShuffleFrame frame = new ShuffleFrame();




    frame.canvas.invalidate();

    Card __dummyCard;
    // state variables 
    GameState gameState = new GameState();
    Printer printer = new Printer(gameState);

    // Setup Block 

    // Game Loop 
    while (true) {
      // Perform Player turn code 


      // win condition 
      if (true == true) {
        break;
      }

      // Increment currentPlayer for next turn 
      gameState.incrementPlayer();
    }

    // Game Finished 
    System.out.println("Player " + (gameState.currentPlayer().id() + 1) + " WINS!");
  }



  public static void main(String[] args) {
    try {
      executeGame();
    } catch (ShuffleException e) {
      System.err.println("Game Error: " + e.getMessage());
    }
  }
}
