package Shuffle.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;

public class Number_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_ydd9ch_a(editorContext, node);
  }

  private EditorCell createCollection_ydd9ch_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_ydd9ch_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_ydd9ch_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ydd9ch_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ydd9ch_c0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_ydd9ch_d0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_ydd9ch_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Number ");
    editorCell.setCellId("Constant_ydd9ch_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_ydd9ch_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "{name} ");
    editorCell.setCellId("Constant_ydd9ch_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_ydd9ch_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "is ");
    editorCell.setCellId("Constant_ydd9ch_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_ydd9ch_d0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("value");
    provider.setNoTargetText("<no value>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_value");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
}
