package ShuffleJava.runtime;

/*Generated by MPS */


public class Button {

  private boolean isClicked;
  private String name;


  public Button(String name) {
    this.name = name;
    this.isClicked = false;
  }



  public boolean isClicked() {
    return isClicked;
  }



  public boolean setClicked(boolean click) {
    return this.isClicked = click;
  }

  public String getName() {
    return this.name;
  }
}
