package ShuffleJava.runtime;

/*Generated by MPS */


public abstract class CardPileUtil {
  public static void move(int num, CardPile pile1, CardPile pile2) {
    for (int i = 0; i < num; i++) {
      Card c;
      c = pile1.draw();
      pile2.add(c);
    }
  }
}
