package ShuffleJava.runtime;

/*Generated by MPS */


public abstract class CardPileUtil {
  public static void move(int num, CardPile pile1, CardPile pile2) {
    for (int i = 0; i < num; i++) {
      Card c;
      c = pile1.draw();
      pile2.add(c);
    }
    System.out.println(num + " cards are moved from " + pile1 + "(size after move = " + pile1.size() + ")" + " to " + pile2 + "(size after move = " + pile2.size() + ")");

  }



  public static void move(Card c, CardPile pile1, CardPile pile2) {
    if (!(pile1.checkCard(c))) {
      System.out.println(c + " is not in " + pile1);
      // TODO:need to throw exception here 
      return;
    }
    pile1.removeCard(c);
    pile2.add(c);
    System.out.println(c + " is moved from " + pile1 + "(size after move = " + pile1.size() + ")" + " to " + pile2 + "(size after move = " + pile2.size() + ")");
  }



  public static void moveAll(CardPile pile1, CardPile pile2) {
    System.out.println("All cards are moved from " + pile1 + " to " + pile2);
    int pile1Size = pile1.size();
    for (int i = 0; i < pile1Size; i++) {
      pile2.add(pile1.draw());
    }
  }
}
