package ShuffleJava.runtime;

/*Generated by MPS */

import java.util.ArrayList;

public class CardPile {
  private ArrayList<Card> pile;

  public CardPile() {
    pile = new ArrayList<Card>();
  }



  public void add(Card card) {
    pile.add(card);
  }



  public Card draw() {
    Card c;
    c = pile.get(pile.size() - 1);
    pile.remove(pile.size() - 1);
    return c;
  }

  public void shuffle() {
  }
}
