package ShuffleJava.runtime;

/*Generated by MPS */


public class Card {
  private String rank;
  private String suit;

  public Card(String rankeI, String suitI) {
    suit = suitI;
    rank = rankeI;
  }
}
