package ShuffleJava.runtime;

/*Generated by MPS */

import java.util.ArrayList;
import java.util.Collections;

public class CardPile {

  private ArrayList<Card> pile;
  private boolean faceup;
  private String name;
  private int maxSelectionSize;
  private ArrayList<Card> selection;


  public CardPile(String name) {
    pile = new ArrayList<Card>();
    this.name = name;
    if (name.equals("standard_deck")) {
      System.out.println("standard_deck is used for CardSet");
    }
  }

  public CardPile(CardPile cardpile) {
    pile = new ArrayList<Card>();
    for (Card c : cardpile.getArrayList()) {
      this.pile.add(c);
    }
    this.faceup = cardpile.isFaceup();
    this.name = cardpile.name;
  }



  public String getName() {
    return this.name;
  }



  public boolean isFaceup() {
    return this.faceup;
  }



  public CardPile(String name, boolean faceup) {
    pile = new ArrayList<Card>();
    this.faceup = faceup;
    this.name = name;
    System.out.println("New pile called " + name + " is created");
  }



  public void add(Card card) {
    pile.add(card);
  }



  public void removeCard(Card c) {
    pile.remove(c);
  }



  public Card draw() {
    Card c;
    c = pile.get(pile.size() - 1);
    pile.remove(pile.size() - 1);
    return c;
  }



  public Card getTopCard() {
    Card c;
    c = pile.get(pile.size() - 1);
    return c;
  }



  public boolean checkCard(Card card) {
    for (Card c : pile) {
      if (c.isSameAs(card)) {
        return true;
      }
    }
    return false;
  }



  public void shuffle() {
    System.out.println(name + " is shuffled!");
    Collections.shuffle(pile);
  }



  public ArrayList<Card> getArrayList() {
    return pile;
  }



  public int size() {
    return pile.size();
  }



  public boolean isSelectable() {
    return (this.size() != 0 ? true : false);
  }



  public void setSelectable(boolean b) {
    this.maxSelectionSize = (b ? pile.size() : 0);
  }



  public void setSelectable(int size) {
    this.maxSelectionSize = size;
  }



  /**
   * Adds a card to the selection card collection - this is done when the player selects a card
   */
  private void addSelection(Card card) {
    if (selection.size() < maxSelectionSize) {
      this.selection.add(card);
      card.setSelected(true);
    }
  }



  /**
   * Removes card from the selection card collection - this is done when the player unselects a card
   */
  private void removeSelection(Card card) {
    this.selection.remove(card);
    card.setSelected(false);
  }



  public void toggleSelection(Card c) {
    if (this.selection.contains(c)) {
      removeSelection(c);
    } else {
      addSelection(c);
    }
  }



  public ArrayList<Card> getSelection() {
    return selection;
  }



  public void clearSelection() {
    if (this.selection != null) {
      for (Card c : this.selection) {
        c.setSelected(false);
      }
      this.selection.clear();
    }
    this.maxSelectionSize = 0;
  }



  @Override
  public String toString() {
    String retString = name;
    // <node> 
    return retString;
  }
}
