package ShuffleJava.runtime;

/*Generated by MPS */

import java.util.ArrayList;
import java.util.HashMap;

public class GameState {
  private ArrayList<Player> playerList;
  private int currentPlayer;

  public HashMap<String, CardPile> cardPiles = new HashMap<String, CardPile>();
  public HashMap<String, String> strings = new HashMap<String, String>();
  public HashMap<String, Boolean> booleans = new HashMap<String, Boolean>();


  public GameState() {
    playerList = new ArrayList<Player>();
    currentPlayer = 0;
  }



  public void setNumberPlayers(int numberPlayers) throws ShuffleException {
    System.out.println(numberPlayers + " players are in this game");
    if (numberPlayers < 1) {
      throw new ShuffleException("Invalid number of players: " + numberPlayers);
    }
    for (int x = 0; x < numberPlayers; x++) {
      playerList.add(new Player(x));
    }
  }



  public Player player(int id) {
    // convert 1-indexed to 0-indexed hack 
    return playerList.get(id - 1);
  }



  public Player currentPlayer() {
    return playerList.get(currentPlayer);
  }



  public void incrementPlayer() {
    currentPlayer = (currentPlayer + 1) % playerList.size();
    System.out.print("Player" + (currentPlayer + 1) + " turn:");
  }



  public HashMap whichMap(String variable) {
    if (cardPiles.get(variable) != null) {
      return cardPiles;
    } else if (strings.get(variable) != null) {
      return strings;
    } else {
      return booleans;
    }
  }



  @Override
  public String toString() {
    return "CurrentPlayer is:" + currentPlayer + 1 + "of " + playerList.size() + " number of players";
  }
}
