package ShuffleJava.runtime;

/*Generated by MPS */


public class Player {
  private CardPile hand;
  private int id;
  private int score;
  private boolean human;


  public Player(int id) {
    this.id = id;
    this.human = (id == 0 ? true : false);
    // <node> 
    // <node> 
    // <node> 
    this.hand = new CardPile("player_" + (id + 1));
    this.score = 0;
  }



  public int id() {
    return this.id;
  }



  public CardPile hand() {
    return this.hand;
  }



  public int getScore() {
    return this.score;
  }



  public boolean isHuman() {
    return this.human;
  }



  public int adjustScore(int adjust) {
    return this.score += adjust;
  }



  @Override
  public String toString() {
    return "Player " + id;
  }


}
