package ShuffleJava.runtime;

/*Generated by MPS */

import javax.swing.JFrame;

public class ShuffleFrame {
  public final JFrame frame = new JFrame("Shuffle");


  public ShuffleFrame() {
    frame.pack();
    frame.setSize(800, 600);
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
  }
}
