package ShuffleJava.runtime;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.ImageIcon;

public class ShuffleFrame {
  public final JFrame frame = new JFrame("Shuffle");
  public JLayeredPane jlp;
  public final JPanel canvas = new JPanel(new GridLayout(10, 10), true);

  private static final int FRAME_HEIGHT = 700;
  private static final int FRAME_WIDTH = 800;


  public ShuffleFrame() {
    frame.setVisible(true);
    frame.pack();
    frame.setSize(FRAME_WIDTH, FRAME_HEIGHT);
    frame.setLocationRelativeTo(null);

    jlp = frame.getLayeredPane();
    jlp.setPreferredSize(new Dimension(FRAME_WIDTH, FRAME_HEIGHT));

    ClassLoader classLoader = getClass().getClassLoader();
    JLabel background = new JLabel(new ImageIcon(classLoader.getResource("bg.jpg")));

    jlp.add(background, JLayeredPane.PALETTE_LAYER);

    jlp.add(canvas, JLayeredPane.DEFAULT_LAYER);
  }
}
